package greendao;

import greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VALUE_SOLUTION_SCORE.
 */
public class ValueSolutionScore {

    private Long id;
    private Double score;
    private Long valueId;
    private Long userId;
    private Long solutionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ValueSolutionScoreDao myDao;

    private Value value;
    private Long value__resolvedKey;

    private User user;
    private Long user__resolvedKey;

    private Solution solution;
    private Long solution__resolvedKey;


    public ValueSolutionScore() {
    }

    public ValueSolutionScore(Long id) {
        this.id = id;
    }

    public ValueSolutionScore(Long id, Double score, Long valueId, Long userId, Long solutionId) {
        this.id = id;
        this.score = score;
        this.valueId = valueId;
        this.userId = userId;
        this.solutionId = solutionId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getValueSolutionScoreDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public Long getValueId() {
        return valueId;
    }

    public void setValueId(Long valueId) {
        this.valueId = valueId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getSolutionId() {
        return solutionId;
    }

    public void setSolutionId(Long solutionId) {
        this.solutionId = solutionId;
    }

    /** To-one relationship, resolved on first access. */
    public Value getValue() {
        Long __key = this.valueId;
        if (value__resolvedKey == null || !value__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ValueDao targetDao = daoSession.getValueDao();
            Value valueNew = targetDao.load(__key);
            synchronized (this) {
                value = valueNew;
            	value__resolvedKey = __key;
            }
        }
        return value;
    }

    public void setValue(Value value) {
        synchronized (this) {
            this.value = value;
            valueId = value == null ? null : value.getId();
            value__resolvedKey = valueId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public User getUser() {
        Long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            userId = user == null ? null : user.getId();
            user__resolvedKey = userId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Solution getSolution() {
        Long __key = this.solutionId;
        if (solution__resolvedKey == null || !solution__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SolutionDao targetDao = daoSession.getSolutionDao();
            Solution solutionNew = targetDao.load(__key);
            synchronized (this) {
                solution = solutionNew;
            	solution__resolvedKey = __key;
            }
        }
        return solution;
    }

    public void setSolution(Solution solution) {
        synchronized (this) {
            this.solution = solution;
            solutionId = solution == null ? null : solution.getId();
            solution__resolvedKey = solutionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
