package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VERSUS_RESPONSE.
 */
public class VersusResponse {

    private Long id;
    private Double response;

    public VersusResponse() {
    }

    public VersusResponse(Long id) {
        this.id = id;
    }

    public VersusResponse(Long id, Double response) {
        this.id = id;
        this.response = response;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getResponse() {
        return response;
    }

    public void setResponse(Double response) {
        this.response = response;
    }

}
